image: ruby:2.6.3

before_script:
  - gem install jekyll
  - gem install nodejs
  - npm install bulma
  - npm install bulma-carousel
  - rm -rf node_modules/bulma-carousel/src/demo

pages:
  stage: deploy
  script:
  - sass _sass/main.css css/main.css
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
