image: ruby:2.1

pages:
  script:
    - gem install jekyll
      #- npm install bulma-carousel
      #- rm -rf node_modules/bulma-carousel/src/demo
      #- sass _sass/main.css css/main.css
    - jekyll build -d public/
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - ruby
