# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

see_the_place_gallery:
  - src: inside_shop.jpg
  - src: inside_shop_2.jpg
  - src: inside_shop_door.jpg
#  - id: 4
# src: outside_shop.jpg
  - src: outside_shop_2.jpg

gallery:
  - src: haircut_1.jpg
  - src: haircut_2.jpg
  - src: haircut_3.jpg
  - src: haircut_4.jpg
  - src: haircut_5.jpg

pricing:
  - service: "haircut"
    price: "$20"
  - service: "beard trim"
    price: "$15/$10"
  - service: "buzz"
    price: "$15"
  - service: "skin fade"
    price: "$25"
  - service: "flat top"
    price: "$25"
  - service: "bald (razor)"
    price: "$25"
  - service: "lineup"
    price: "$5/$2"
  - service: "shampoo"
    price: "$5"

# Build settings
markdown: kramdown

collections:
  parts:
    output: true
    relative_path: _parts

include: ['_parts']
